### PR TITLE
Tasks docs

### PR DESCRIPTION
**Pull request by kohend**
Indicate that filtering is a new feature.

### CODE REVIEW

**Comment by bmahler** [comment]
We've removed these docs entirely from the repo since they were very stale and they now get generated as part of the website publishing, you can find them here:

http://mesos.apache.org/documentation/latest/endpoints/

The way we will address what you're adding here is to provide versioned documentation, that work is ongoing here: https://reviews.apache.org/r/52064/ cc @tanderegg

**Comment by bmahler** [comment]
@kohend can you close this PR based on my comment above?

**Comment by kohend** [comment]
Is it relevant to add it to the documentation in the source instead, so that the difference will have better visibility (and people won't have to go through versions to see when it's added)?

**Comment by bmahler** [comment]
@kohend Can you clarify? I'm not sure what you mean.

**Comment by greggomann** [comment]
Closing due to inactivity - reopen if still relevant, thanks!

**Pull request closed without merging**
