### PR TITLE
[MESOS-6038] Prevent memory leaks

### PR DESCRIPTION
**Pull request by aaronjwood**
This should prevent any of the promises that are created in the various `ZookeeperProcess` class methods from leaking memory.

https://reviews.apache.org/r/51068/

### CODE REVIEW

**Comment by haosdent** [comment]
Hi, @aaronjwood Because we use [reviewboard](https://reviews.apache.org/groups/mesos/) to review code changes. Could you follow https://github.com/apache/mesos/blob/master/docs/submitting-a-patch.md to submit your patch?

**Comment by haosdent** [comment]
In addition, I think it would be more helpful to describe more context about the memory leaks here to help others understand this patch.

**Comment by xiaods** [comment]
could you please describe the context about memory leaks and give some testing to confirm the root cause.

**Comment by aaronjwood** [comment]
Hi @haosdent. Sure, I'm sorry. I had created a JIRA and reviewboard account and went to open this PR but should have only included the change to the contributors file.

**Comment by aaronjwood** [comment]
For the context: I had found a few places where these `Promise` objects were leaking. Once the `Future` was returned there was no way to free the memory for the `Promise` object that had been allocated thus causing the leak. I don't have any direct issues with running Mesos that stemmed from this, it's just something that I thought could be fixed.

**Comment by Vish0007** [comment]
@aaronjwood  the "promise" object you have has local scope (and lifetime) and its not valid outside the method; I am sure valgrind wold report this as error;

**Comment by haosdent** [comment]
+1 For what @Vish0007 said. If promise became a locale scope object here, return its future seems incorrect. I search `return \S+\.future\(\);` in all exists code, all `Promise` are member objects or heap objects.

**Comment by aaronjwood** [comment]
I might be misunderstanding things but why can we not do this? I see it being done here https://github.com/apache/mesos/blob/master/3rdparty/libprocess/src/http.cpp#L1001

If we make the `Promise` local like it is in this patch, pass its address into the tuple via the copy constructor (that should be the copy constructor getting called, right?) so that it takes a copy and doesn't rely on an actual address from the stack, and return the future in the same way as the example above, would that not work? Even though the `Promise` is local to the stack, when we return `Future` shouldn't it be a copy of what's needed underneath?

**Comment by haosdent** [comment]
>Even though the Promise is local to the stack, when we return Future shouldn't it be a copy of what's needed underneath?

Sorry, I misunderstanding something before. Future store its data in `std::shared_ptr<Data> data` and your function return a copy instead of const reference, so it should work.

**Comment by aaronjwood** [comment]
No no, that's okay. I appreciate everyone helping me validate these changes. I'm trying to be very careful with this :)

**Comment by haosdent** [comment]
By the way, copy a comment from @jpeach in https://mesos.slack.com/messages/cxx/

```
Promise<int> promise = Promise<int>();

why not just
```Promise<int> promise;```
``

**Comment by aaronjwood** [comment]
I don't have access to their Slack but I agree.

**Comment by haosdent** [comment]
You could join via https://mesos-slackin.herokuapp.com/

**Comment by aaronjwood** [comment]
It looks like I was wrong about this, I had thought the copy constructor of tuple was getting called when it wasn't the copy constructor at all. I did some more testing with this and found that the original version behaves properly.

**Pull request closed without merging**
