### PR TITLE
Replace hardcoded 'http:' in webui code with window.location.protocol

### PR DESCRIPTION
**Pull request by arnaudbriche**
Hi,

In my mesos setup I access mesos webui from on https endpoint which reverse proxy requests to mesos (listening on the private interface ip of the machine); in order to not break internal links in the webui, 
I just replaced the hardcoded 'http:' string with a protocol independent window.location.protocol.
Maybe it can be of interest for some other mesos users.

### CODE REVIEW

**Comment by bmahler** [comment]
Thanks Arnaud! Nice, there will be built-in HTTPS support in Mesos at some point, you may want to chime in here:

https://issues.apache.org/jira/browse/MESOS-1825

**Comment by akerekes** [comment]
Is there a plan to include this PR in the meantime before actual HTTPS support is implemented?

**Comment by akerekes** [comment]
@arnaudbriche There is one more location where this needs to be fixed:
https://github.com/apache/mesos/blob/master/src/webui/master/static/browse.html#L71
It should be:
```
href="//{{slave_host}}/files/download.json?path={{encodeURIComponent(file.path)}}">
```

**Comment by arnaudbriche** [comment]
Thanks @akerekes for pointing this out.
It should also be noted that when one tries to connect to a non-leader node, mesos (server-side) issue a 301 Redirect with an hardcoded http:// protocol. 
I did took a quick look at the C++ code,  but didn't find an easy way to fix it though.

**Comment by jfarrell** [comment]
Closing per request at https://s.apache.org/V8r3

**Pull request closed without merging**
