### PR TITLE
[MESOS-10199] Cherry-Pick: Fix Host field in client headers

### PR DESCRIPTION
**Pull request by zorro786**

### CODE REVIEW

**Comment by zorro786** [comment]
@vinodkone This is a cherry pick for 1.7.x branch. Please merge when you get a chance.

**Comment by vinodkone** [comment]
@zorro786 1.7.x is technically EOL so we likely wont be making any releases off the branch. Do you still want it in 1.7.x? Also, if you are backporting this, we need backports to all the release branches that are still supported (as of today thats 1.9.x, 1.10.x, 1.11.x)

**Comment by zorro786** [comment]
@vinodkone Yeah per discussion in Slack, we would like to backport this to 1.7.x. I have raised PRs for 1.9.x, 1.10.x and 1.11.x: https://github.com/apache/mesos/pull/373, https://github.com/apache/mesos/pull/374, https://github.com/apache/mesos/pull/375

**Review by kamaradclimber — APPROVED** [review]

**Comment by kamaradclimber** [comment]
@zorro786 are you still interested?

**Comment by cf-natali** [comment]
Closing for staleness.

**Pull request closed without merging**
