### PR TITLE
Fixed cpplint errors.

### PR DESCRIPTION
**Pull request by cf-natali**

### CODE REVIEW

**Comment by cf-natali** [comment]
@qianzhangxa 
I don't seem to have merge permissions yet?

**Comment by qianzhangxa** [comment]
> I don't seem to have merge permissions yet?

@cf-natali What we usually do is to run `support/apply-reviews.py -g <PR-number>` (e.g. `support/apply-reviews.py -g 403` for this PR) to apply the changes of a PR on top of the latest code of `master` branch, and then run `git push` to push the commit to the remote (https://gitbox.apache.org/repos/asf/mesos.git) which will also automatically close the PR. I think you already have the push permission now. Once the commit gets pushed, it will also trigger a build in https://builds.apache.org/job/Mesos/job/Mesos-Buildbot/, we need to check if that build has any failures.

Please note, https://github.com/apache/mesos.git is just a mirror of https://gitbox.apache.org/repos/asf/mesos.git, so I do not think we should directly merge MRs in it.

Please also add yourself into https://github.com/apache/mesos/blob/master/docs/committers.md, thanks!

**Comment by qianzhangxa** [comment]
@cf-natali And I think you do need the write permission of the following two projects so you can close stale PRs for 1 and may need to merge PRs for 2.

1. https://github.com/apache/mesos
2. https://github.com/apache/mesos-site

To get the write permission, you need to link your GitHub and Apache accounts via https://gitbox.apache.org/setup/.

**Comment by cf-natali** [comment]
Thanks!

If this looks OK to you I'll merge :).

**Pull request merged**
