### PR TITLE
Update presentations.md

### PR DESCRIPTION
**Pull request by packtpartner**
Added a new Video course.

### CODE REVIEW

**Comment by bmahler** [comment]
Perhaps we need to introduce a paid section in this page for this type of content? Other PMC members have thoughts here?

**Comment by jpeach** [comment]
@bmahler Maybe a "training" section?

**Comment by bmahler** [comment]
@packtpartner can you add this under a new 'Training' section at the bottom?

**Comment by packtpartner** [comment]
@bmahler Done.
Link to the pull request - https://github.com/apache/mesos/pull/251

**Comment by bmahler** [comment]
Thanks, can you close this PR in favor of that one?

**Comment by vinodkone** [comment]
@packtpartner Can you close this please?

**Pull request closed without merging**
