### PR TITLE
Explicitely fail content length fetch in case of error

### PR DESCRIPTION
**Pull request by Lqp1**
Fetching artifacts is done in two steps:
* use a HEAD request to get size of the remote object
* allocate needed space on disk (by eventually removing old cached data)
* fetch artifact
* validate size of fetched artifact and adapt cache behavior if there is no match (but it's outside the scope of this PR)

The issue takes place if the remote server does not answer properly to HEAD request (ie a 404 or a 500), the current code will return the size of the 404 or 500 page as if it was the size of the artifact.
There is no "real" issue now that #414 is merged, but there could still be some rare issues if the artifact is significantly larger and available cache is too small (Mesos would write more on disk than configured for its cache).

This patch will make Mesos fail sooner if HEAD request fails, but most of the time this is not an issue as the second request (GET) will fail too anyway.

### CODE REVIEW

**Comment by andreaspeters** [comment]
@cf-natali @qianzhangxa  can u help here?

**Comment by andreaspeters** [comment]
@cf-natali for me it looks fine and with the response code handling more "nice" then before. :+1:

**Comment by cf-natali** [comment]
Hey,

I need to think about this a bit ore, I'm a bit concerned about the potential non backward-compatibility.

**Comment by andreaspeters** [comment]
May I asked where you see potential backward compatibility problems?

**Comment by cf-natali** [comment]
One possibility is the server returning the correct `Content-Length`, but returning a non-`200` status.

It'd be a bit weird but who knows.

Also, as explained by @Lqp1, the following `GET` will fail anyway in case of error - and generally relying on `HEAD`/`Content-Length` is fragile since it's not atomic: the file could be modified between the `HEAD` and the `GET`.

So given the risk of breakage, and the limited impact since the downstream problem has been fixed, I'd be tempted to ignore.

**Comment by andreaspeters** [comment]
Ok, I understand. More risk then we can win makes also no sense for me. But in these case, I think we should close these PR. :-)

**Comment by Lqp1** [comment]
Hello :)
Thanks for your feedback.

> the file could be modified between the HEAD and the GET.

**Comment by cf-natali** [comment]
> Just FYI, we are now running this patch in production, without any issue so far.

Yes - I'm sure it works as intended in your environment, the problem is guaranteeing it will won't regress anywhere :).

I'm closing, but thanks for the contribution!

**Pull request closed without merging**
