### PR TITLE
Remove missing MUGs from site

### PR DESCRIPTION
**Pull request by pleia2**
The Beijing, Sevilla, Albany and Austin MUGs no longer exist on
Meetup, removing.

### CODE REVIEW

**Comment by bmahler** [comment]
I have the following error from our tooling when pulling this down:

./support/apply-reviews.py -g 253
Cookie coming from patch-diff.githubusercontent.com attempted to set domain to github.com
2018-01-11 18:13:31 URL:https://patch-diff.githubusercontent.com/raw/apache/mesos/pull/253.patch [1750] -> "253.patch" [1]
fatal: --author 'Elizabeth' is not 'Name <email>' and matches no existing author

Do you have an email address you would like to include, or could you update the PR to have a commit with your email included?

**Comment by pleia2** [comment]
Sorry about that! Email address should be lyz@princessleia.com

**Comment by bmahler** [comment]
No worries! I just realized that the tooling left behind some dirty state and these changes were pulled into the next PR I committed: 370b5b634d1132a34022ec184a3056de46b45c4a.

Sorry about that! :( Are you able to close this?

**Comment by pleia2** [comment]
Sure thing, closing.

**Pull request closed without merging**
